CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name VARCHAR(100) NOT NULL,
                           email VARCHAR(254) NOT NULL,
                           phone VARCHAR(40) NOT NULL,
                           CONSTRAINT ck_customers_full_name_not_blank
                               CHECK (btrim(full_name) <> ''),
                           CONSTRAINT ck_customers_email_not_blank
                               CHECK (btrim(email) <> ''),
                           CONSTRAINT ck_customers_phone_not_blank
                               CHECK (btrim(phone) <> '')
);

CREATE TABLE tent_types (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            width_feet INTEGER NOT NULL,
                            length_feet INTEGER NOT NULL,
                            total_quantity INTEGER NOT NULL,
                            CONSTRAINT uq_tent_types_dimensions
                                UNIQUE (width_feet, length_feet),
                            CONSTRAINT ck_tent_types_width
                                CHECK (width_feet BETWEEN 10 AND 40),
                            CONSTRAINT ck_tent_types_length
                                CHECK (length_feet BETWEEN 10 AND 40),
                            CONSTRAINT ck_tent_types_dimension_order
                                CHECK (width_feet <= length_feet),
                            CONSTRAINT ck_tent_types_quantity
                                CHECK (total_quantity > 0)
);

CREATE UNIQUE INDEX uq_customers_email_lower
    ON customers (lower(email));

CREATE TABLE reservations (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              customer_id BIGINT NOT NULL,
                              tent_type_id BIGINT NOT NULL,
                              quantity INTEGER NOT NULL,
                              event_start TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              event_end TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              reserved_from TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              reserved_until TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              location VARCHAR(250) NOT NULL,
                              status VARCHAR(20) NOT NULL,
                              version BIGINT NOT NULL DEFAULT 0,
                              CONSTRAINT fk_reservations_customer
                                  FOREIGN KEY (customer_id) REFERENCES customers (id),
                              CONSTRAINT fk_reservations_tent_type
                                  FOREIGN KEY (tent_type_id) REFERENCES tent_types (id),
                              CONSTRAINT ck_reservations_quantity
                                  CHECK (quantity > 0),
                              CONSTRAINT ck_reservations_event_range
                                  CHECK (event_end > event_start),
                              CONSTRAINT ck_reservations_reserved_range
                                  CHECK (reserved_until > reserved_from),
                              CONSTRAINT ck_reservations_window_contains_event
                                  CHECK (
                                      reserved_from <= event_start
                                          AND reserved_until >= event_end
                                      ),
                              CONSTRAINT ck_reservations_location_not_blank
                                  CHECK (btrim(location) <> ''),
                              CONSTRAINT ck_reservations_status
                                  CHECK (
                                      status IN (
                                                 'PENDING',
                                                 'CONFIRMED',
                                                 'WAITLISTED',
                                                 'REJECTED',
                                                 'CANCELLED',
                                                 'COMPLETED'
                                          )
                                      )
);

CREATE TABLE maintenance_blocks (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    tent_type_id BIGINT NOT NULL,
                                    quantity_unavailable INTEGER NOT NULL,
                                    blocked_from TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                                    blocked_until TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                                    reason VARCHAR(250) NOT NULL,
                                    CONSTRAINT fk_maintenance_blocks_tent_type
                                        FOREIGN KEY (tent_type_id) REFERENCES tent_types (id),
                                    CONSTRAINT ck_maintenance_quantity
                                        CHECK (quantity_unavailable > 0),
                                    CONSTRAINT ck_maintenance_range
                                        CHECK (blocked_until > blocked_from),
                                    CONSTRAINT ck_maintenance_reason_not_blank
                                        CHECK (btrim(reason) <> '')
);

CREATE TABLE waitlist_entries (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  reservation_id BIGINT NOT NULL,
                                  joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                                  CONSTRAINT fk_waitlist_entries_reservation
                                      FOREIGN KEY (reservation_id)
                                          REFERENCES reservations (id) ON DELETE CASCADE,
                                  CONSTRAINT uq_waitlist_entries_reservation
                                      UNIQUE (reservation_id)
);

CREATE INDEX idx_reservations_availability
    ON reservations (
                     tent_type_id,
                     status,
                     reserved_from,
                     reserved_until
        );

CREATE INDEX idx_reservations_customer
    ON reservations (customer_id);

CREATE INDEX idx_maintenance_availability
    ON maintenance_blocks (
                           tent_type_id,
                           blocked_from,
                           blocked_until
        );

CREATE INDEX idx_waitlist_order
    ON waitlist_entries (
                         joined_at,
                         id
        );