-- User accounts authenticate people without putting passwords on Customer rows.
CREATE TABLE user_accounts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               email VARCHAR(254) NOT NULL,
                               password_hash VARCHAR(100) NOT NULL,
                               role VARCHAR(20) NOT NULL,
                               customer_id BIGINT,
                               enabled BOOLEAN NOT NULL DEFAULT TRUE,
                               created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                               version BIGINT NOT NULL DEFAULT 0,

                               CONSTRAINT fk_user_accounts_customer
                                   FOREIGN KEY (customer_id) REFERENCES customers (id),

    -- One customer profile can belong to at most one login account.
                               CONSTRAINT uq_user_accounts_customer UNIQUE (customer_id),

                               CONSTRAINT ck_user_accounts_email_not_blank
                                   CHECK (btrim(email) <> ''),

                               CONSTRAINT ck_user_accounts_password_hash_not_blank
                                   CHECK (btrim(password_hash) <> ''),

                               CONSTRAINT ck_user_accounts_role
                                   CHECK (role IN ('CUSTOMER', 'STAFF', 'ADMIN')),

    -- CUSTOMER accounts require a customer profile.
    -- STAFF and ADMIN accounts must not impersonate a customer profile.
                               CONSTRAINT ck_user_accounts_customer_link
                                   CHECK (
                                       (role = 'CUSTOMER' AND customer_id IS NOT NULL)
                                           OR (role IN ('STAFF', 'ADMIN') AND customer_id IS NULL)
                                       )
);

-- Email identity is case-insensitive.
CREATE UNIQUE INDEX uq_user_accounts_email_lower
    ON user_accounts (lower(email));

-- Audit events record security and lifecycle actions without storing secrets.
CREATE TABLE audit_events (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                              request_id UUID NOT NULL,
                              actor_user_id BIGINT,
                              actor_email VARCHAR(254) NOT NULL,
                              action VARCHAR(80) NOT NULL,
                              resource_type VARCHAR(80) NOT NULL,
                              resource_id VARCHAR(100),
                              old_status VARCHAR(20),
                              new_status VARCHAR(20),
                              outcome VARCHAR(20) NOT NULL,
                              details VARCHAR(500),

                              CONSTRAINT fk_audit_events_actor
                                  FOREIGN KEY (actor_user_id)
                                      REFERENCES user_accounts (id),

                              CONSTRAINT ck_audit_events_actor_email_not_blank
                                  CHECK (btrim(actor_email) <> ''),

                              CONSTRAINT ck_audit_events_action_not_blank
                                  CHECK (btrim(action) <> ''),

                              CONSTRAINT ck_audit_events_resource_type_not_blank
                                  CHECK (btrim(resource_type) <> ''),

                              CONSTRAINT ck_audit_events_old_status
                                  CHECK (
                                      old_status IS NULL OR old_status IN (
                                                                           'PENDING',
                                                                           'CONFIRMED',
                                                                           'WAITLISTED',
                                                                           'REJECTED',
                                                                           'CANCELLED',
                                                                           'COMPLETED'
                                          )
                                      ),

                              CONSTRAINT ck_audit_events_new_status
                                  CHECK (
                                      new_status IS NULL OR new_status IN (
                                                                           'PENDING',
                                                                           'CONFIRMED',
                                                                           'WAITLISTED',
                                                                           'REJECTED',
                                                                           'CANCELLED',
                                                                           'COMPLETED'
                                          )
                                      ),

                              CONSTRAINT ck_audit_events_outcome
                                  CHECK (outcome IN ('SUCCEEDED', 'FAILED'))
);

-- Supports recent-first administrator audit queries.
CREATE INDEX idx_audit_events_recent
    ON audit_events (occurred_at DESC, id DESC);

-- Supports investigating activity by a specific authenticated account.
CREATE INDEX idx_audit_events_actor
    ON audit_events (actor_user_id, occurred_at DESC);

-- Lets the scheduler efficiently find due confirmed reservations.
CREATE INDEX idx_reservations_due_completion
    ON reservations (reserved_until, id)
    WHERE status = 'CONFIRMED';

-- Application users may append audit events but may not rewrite history.
CREATE FUNCTION reject_audit_event_mutation()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only';
END;
$$;

CREATE TRIGGER audit_events_append_only
    BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW
EXECUTE FUNCTION reject_audit_event_mutation();